//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error
    {
        public int ErrorID { get; set; }
        public string ErrorCode { get; set; }
        public string Message { get; set; }
        public int Severity { get; set; }
    }
}
