//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblImageDetail
    {
        public string id { get; set; }
        public string ImageName { get; set; }
        public string ImageData { get; set; }
        public string ImageDescription { get; set; }
        public Nullable<System.DateTime> ImageDate { get; set; }
        public string ImageLocation { get; set; }
    }
}
